version: '3'
services:
  api:
    container_name: api
    image: node:12.14.1
    build: .
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: npm run start:dev
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ezrealtors
      MYSQL_DATABASE: ezrealtors
      MYSQL_USER: ezrealtors
      MYSQL_PASSWORD: ezrealtors
